#!/usr/bin/env python3
"""Render the final, persisted migration audit without mutating source assets."""
import collections,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
r=json.loads((ROOT/'reports/cobblemon-1.8-audit.json').read_text())
rows=r['models'];upgraded=[x for x in rows if x['result'].startswith('uses')];retained=[x for x in rows if x['result'].startswith('retained')]
lines=['# Cobblemon 1.8 model test checklist','',f'Compared `{r["old_revision"]}` with official 1.8.0 `{r["new_revision"]}`.','',f'**{len(rows)} upstream new/changed geometry files: {len(upgraded)} use 1.8 geometry, {len(retained)} retain custom/legacy geometry.**',f'{len(r["removed_identical"])} identical upstream resources removed ({sum(x["bytes"] for x in r["removed_identical"]):,} raw bytes). {len(r.get("canonical_path_moves",[]))} byte-preserving resource moves make retained overrides occupy upstream paths, avoiding basename collisions.','', 'Test normal/shiny, all forms, walking/idle, swimming/flying, battle/fainting, shoulder/riding where available, and each owned skin. Legacy geometry keeps skins usable while they await retargeting; new animation/poser code still requires in-game checks.','', '## Models now supplied by Cobblemon 1.8','','Every geometry entry below is new or changed upstream and has no remaining pack geometry override. A retained custom poser/animation may still apply; inspect the full audit for resource paths.','','| Tested | Model | Upstream change |','|---|---|---|']
lines += [f'| [ ] | `{x["model"]}` | {x["upstream_change"]} |' for x in upgraded]
lines += ['','## Models retained for custom/legacy compatibility','','These are not counted as upgraded geometry. Test custom skins and their inherited animations on 1.8.','','| Tested | Model | Upstream change |','|---|---|---|']
lines += [f'| [ ] | `{x["model"]}` | {x["upstream_change"]} |' for x in retained]
counts=collections.Counter(x['species'] for x in r['pinned_legacy'])
lines += ['','## Texture-only skin families pinned to old base dependencies','', ', '.join('`'+s+'`' for s in sorted(counts))+'.','',f'{len(r["pinned_legacy"])} paired geometry/poser/animation/texture/resolver files were added; their original paths and reasons are recorded in the JSON audit. Canonical moves may subsequently relocate a path or remove an identical upstream copy.','', '## Existing same-ID duplicates resolved','']
lines += ['- `'+x['name']+'`: '+x['reason']+'. Original retained in `'+x['quarantine_path']+'`.' for x in r.get('local_duplicate_resolution',[])]
lines += ['','## Asset repairs and remaining missing artwork','']
lines += ['- `'+x['path']+'`: '+x['reason']+'.' for x in r.get('repaired_references',[])]
refs=json.loads((ROOT/'reports/resource-reference-check.json').read_text())
for texture, paths in refs['missing_textures'].items():lines.append('- **Missing artwork** `'+texture+'`; referenced by '+', '.join('`'+p+'`' for p in paths)+'.')
lines += ['','No missing geometry references were found. The missing Zygarde abyss normal/emissive and Mega Venusaur movie normal art was also absent from the sibling pack ZIP, quarantine, client resources, Cobblemon and local Mega projects. Existing authored references remain in place.','', '## Client/server split acceptance checks','', '- [ ] New client starts with the built-in baseline enabled and renders tags, inventories and existing skins without a server pack.', '- [ ] Join using the small overlay, verify fonts/inventory screens and several ordinary/custom Pokémon.', '- [ ] Change one existing skin and add one new tag/resolver at its normal source path, rebuild only the server pack, and verify both without a client update.', '- [ ] Delete a temporary custom-only resource and its references; verify the generated resource filter hides the client baseline copy.', '- [ ] Verify the complete fallback pack on a client without the baseline before transitioning older clients.', '', 'Baseline bundling removes the large repeated download. Minecraft may still reload all packs when joining; it does not remove all reload time or GPU texture memory usage.','','File-level SHA-256, exact removals, retained paths and normalization records: [cobblemon-1.8-audit.json](cobblemon-1.8-audit.json). Complete frozen asset list: [client-baseline.json](../client-baseline.json). Size results: [asset-size-report.json](asset-size-report.json).']
(ROOT/'reports/cobblemon-1.8-model-test-list.md').write_text('\n'.join(lines)+'\n')
print(f'{len(upgraded)} native updates, {len(retained)} retained models, {len(r.get("canonical_path_moves",[]))} moves')
